### ISSUE TITLE
Сменить почту для обратной связи

### ISSUE THREAD

**Issue by artemkonenko** [mmcs-sfedu/mmcs-schedule#5]
В коде [ScheduleActivity.java](https://github.com/mmcs-sfedu/mmcs-schedule/blob/96487345891e85ebfcc07dff7d464575f13466e4/app/src/main/java/com/nolan/mmcs_schedule/ui/schedule_activity/ScheduleActivity.java#L170) захардкожена почта утратившая в какой-то момент актуальность. Пожалуй, стоит завести в домене sfedu.ru отдельную почту для расписания и указать её (попутно переместив соответствующую строку из кода в файл с ресурсами).

**Comment by NolanDeveloper** [comment]
Окок.
